# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=200),
        ),
    ]
