# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170923_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='body',
        ),
    ]
